here      := $(shell pwd)
rootname  := cpp_projects/
root      := $(shell expr $(here) : '\(.*$(rootname)\)')



hpaths    :=
hpaths    += $(root)jess/inc

lpaths    :=
lpaths    += $(root)jess/lib/lin64

defines   := 

libraries :=
libraries += jess


-include $(root)make/Makefile.Bin.mk
